title: <p align="center">Kody Hedder</p> # your name (or website title) here
logo: "/images/13173204_10154102296906000_6651992541583427058_o.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">Established and dedicated professional with developed skill set to excel within GIS Analyst / Technician role.</p> 
  <br><br>
  <p align="justify">As an accomplished GIS expert, I carry extensive hands-on experience using GIS to successfully collect and analyse geographical information for a wide variety of projects. In addition to my broad technical knowledgebase and ability to conduct complex statistical analyses, I am also an effective communicator and team player who is skilled at collaborating with diversely functional colleagues to manage on-site activities, collect and record detailed information, and accomplish all project goals ahead of schedule. I have also mastered versatile time-management strategies and possess the dedication to overcome any challenge in my path.</p>
  <br><br>
  <a href="https://www.linkedin.com/in/kody-hedder-4bb59a11a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
