title: <p align="center">Kody Hedder</p> # your name (or website title) here
logo: "/images/Kody_img.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">Established and dedicated professional with developed skill set to excel within GIS Analyst / Technician role.</p> 
  <br><br>
  <div align="justify">
  <p>As an accomplished GIS expert, I carry extensive hands-on experience using GIS to successfully collect and analyse geographical information for a wide variety of projects.</p> 
  <p>In addition to my broad technical knowledgebase and ability to conduct complex statistical analyses, I am also an effective communicator and team player who is skilled at collaborating with diversely functional colleagues to manage on-site activities, collect and record detailed information, and accomplish all project goals ahead of schedule.</p>
  <p>I have also mastered versatile time-management strategies and possess the dedication to overcome any challenge in my path.</p>
  </div>
  <br><br>
  <a href="https://www.linkedin.com/in/kody-hedder-4bb59a11a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
